apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: de-ai-03

resources:
- ../../base

commonLabels:
  environment: dev

images:
- name: WAS_IMAGE
  newName: 827913617635.dkr.ecr.ap-southeast-1.amazonaws.com/de-ai-03-devops-tf-eks-auto-dev/was
  newTag: ab075cddd8eb
- name: WEB_IMAGE
  newName: 827913617635.dkr.ecr.ap-southeast-1.amazonaws.com/de-ai-03-devops-tf-eks-auto-dev/web
  newTag: ab075cddd8eb
